/**
 * This file demonstrates the concept of companion objects in Kotlin.
 *
 * Companion objects are singleton objects for a class. They can be used to provide utility functions,
 * such as factory methods, that support the concept modeled by the class. They are similar to static
 * content in Java or C# classes.
 *
 * A companion object:
 * - Is defined within the body of the class.
 * - Is marked as a companion object.
 * - Does not have a name.
 *
 * Companion objects are useful for housekeeping behavior, factory operations, shared data across all
 * instances of a class, etc. From the user's perspective, the companion object and the class appear
 * as a single concept.
 */

class UserSession private constructor(val id: Int) {

    // Companion (singleton) object
    companion object {
        private val MAX = 100
        private var count = 0

        // Increment count
        private fun next() = count++

        // Factory method to create a new UserSession
        fun create(): UserSession {
            return UserSession(count).also { next() }
        }
    }

    // Member function to print session data
    fun printData() {
        println("Id is $id and MAX is $MAX")
    }

    // Override toString method
    override fun toString(): String {
        return "UserSession($id)"
    }
}

/**
 * The main function demonstrates the creation and use of UserSession instances
 * using the companion object's factory method.
 */
fun main() {
    // Create UserSession instances using the companion object's factory method
    val session1 = UserSession.create()
    println(session1)

    val session2 = UserSession.create()
    println(session2)

    // Print data of the first session
    session1.printData()
}

/*
 * Output:
 * UserSession(0)
 * UserSession(1)
 * Id is 0 and MAX is 100
 */

/**
 * Explanation:
 *
 * - The `UserSession` class has a private constructor, so it cannot be instantiated directly from outside the class.
 * - The companion object within `UserSession` provides a `create()` factory method to create new instances.
 * - The `next()` function increments the `count` variable, ensuring each session has a unique ID.
 * - The `printData()` method displays the session ID and the `MAX` value.
 * - The companion object acts as a singleton, controlling the creation of `UserSession` instances.
 */


/**
 * Summary:
 * Companion Object: The companion object is a singleton object tied to the UserSession class. It provides utility functions like the create() factory method that controls how instances of UserSession are created.
 *
 * Private Constructor: The constructor of UserSession is private, so instances cannot be created directly from outside the class. Instead, they must be created using the create() method provided by the companion object.
 *
 * Output: The main function demonstrates how to create and use UserSession instances. The unique session IDs are generated by the companion object's create() method, and session data is printed using the printData() method.
 *
 * This class.kt file gives a complete and structured example of how to use companion objects in Kotlin, along with detailed comments and explanations.
 */